### ISSUE TITLE
No result when using script

### ISSUE THREAD

**Issue by alact** [Ceryn/img#3]
I run the script and receive no output, scrot, xclip, and curl are Ok.
I tried to preform scrot -z /tmp/  
scrot -z /tmp/
giblib error: Saving to file /tmp/ failed

**Comment by Ceryn** [comment]
Hey, thanks for the heads-up, I'll check it out tomorrow.

On 20 February 2016 19:28:54 CET, alact notifications@github.com wrote:

> I run the script and receive no output, scrot, xclip, and curl are Ok.
> I tried to preform scrot -z /tmp/  
> scrot -z /tmp/
> giblib error: Saving to file /tmp/ failed
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Ceryn/img/issues/3

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Ceryn** [comment]
Hi again. Completely forgot. The script works fine here.
On successful completion, the script will make a beep sound (which you may have muted) and put the URL of the uploaded image in your clipboard. It will make no other output. I suspect you simply missed the URL in your clipboard.

As for `scrot -z /tmp/`, that will try to save the image to the path /tmp/. There are all sorts of issues with this. The script creates a unique filename inside /tmp/ (such as /tmp/img-123456.png) and uses that as the save path. You are supposed to call the script like so:
./img [-s]
Where -s is optional, and will simply be passed on to scrot in case you want to make a manual selection.

I believe the issue was simply a misunderstanding and hope it has now been cleared up. Otherwise please do get back to me with additional details and how I can reproduce the error.
